const defaultStyles = [
    { name: 'Altbier'},
    { name: 'Amber'},
    { name: 'American Amber Ale'},
    { name: 'American Barleywine'},
    { name: 'American Brown Ale'},
    { name: 'American IPA'},
    { name: 'American Lager'},
    { name: 'American Light Lager'},
    { name: 'American Pale Ale'},
    { name: 'American Porter'},
    { name: 'American Stout'},
    { name: 'American Strong Ale'},
    { name: 'American Wheat Beer'},
    { name: 'Australian Sparkling Ale'},
    { name: 'Baltic Porter'},
    { name: 'Belgian Blond Ale'},
    { name: 'Belgian Dark Strong Ale'},
    { name: 'Belgian Dubbel'},
    { name: 'Belgian Golden Strong Ale'},
    { name: 'Belgian IPA'},
    { name: 'Belgian Pale Ale'},
    { name: 'Belgian Tripel'},
    { name: 'Berliner Weisse'},
    { name: 'Best Bitter'},
    { name: 'Black IPA'},
    { name: 'Blonde Ale'},
    { name: 'British Brown Ale'},
    { name: 'British Golden Ale'},
    { name: 'British Strong Ale'},
    { name: 'Brown IPA'},
    { name: 'California Common'},
    { name: 'Cream Ale'},
    { name: 'Dark Mild'},
    { name: 'Doppelbock'},
    { name: 'Double IPA'},
    { name: 'Dunkel'},
    { name: 'Dunkles Bock'},
    { name: 'Dunkleweizen'},
    { name: 'Eisbock'},
    { name: 'English Barleywine'},
    { name: 'English IPA'},
    { name: 'English Porter'},
    { name: 'Festbier'},
    { name: 'Flanders Red Ale'},
    { name: 'Foreign Extra Stout'},
    { name: 'Fruit Lambic'},
    { name: 'German Pils'},
    { name: 'Gose'},
    { name: 'Helles Bock'},
    { name: 'Dortmunder'},
    { name: 'Imperial Stout'},
    { name: 'Irish Extra Stout'},
    { name: 'Irish Red Ale'},
    { name: 'Irish Stout'},
    { name: 'Kentucky Common'},
    { name: 'Kölsch'},
    { name: 'Lambic'},
    { name: 'Märzen'},
    { name: 'Milk Stout'},
    { name: 'Munich Dunkel'},
    { name: 'Munich Helles'},
    { name: 'Oatmeal Stout'},
    { name: 'Old Ale'},
    { name: 'Ordinary Bitter'},
    { name: 'Porter'},
    { name: 'Pre-Prohibition Lager'},
    { name: 'Rauchbier'},
    { name: 'Red IPA'},
    { name: 'Rye IPA'},
    { name: 'Saison (dark) (standard)'},
    { name: 'Saison (pale) (standard)'},
    { name: 'Saison (pale) (super)'},
    { name: 'Saison (pale) (table)'},
    { name: 'Schwarzbier'},
    { name: 'Scottish Export'},
    { name: 'Scottish Heavy'},
    { name: 'Scottish Light'},
    { name: 'Strong Bitter'},
    { name: 'Sweet Stout'},
    { name: 'Trappist Single'},
    { name: 'Tropical Stout'},
    { name: 'Vienna Lager'},
    { name: 'Wee Heavy'},
    { name: 'Weissbier'},
    { name: 'Weizenbock'},
    { name: 'Wheatwine'},
    { name: 'White IPA'},
    { name: 'Witbier'},
];

const defaultBeers = [
    {
        name: 'Hopslam',
        brewery: 'Bells',
        ABV: '10.3',
        IBU: '65',
    }
];

const defaultBreweries = [
    {
        name: 'Bells',
        city: 'Kalamazoo',
        state: 'MI'
    },
    {
        name: 'Mad Tree',
        city: 'Cincinnati',
        state: 'OH'
    },
    {
        name: 'Warped Wing',
        city: 'Dayton',
        state: 'OH'
    },
];
